### ISSUE TITLE
[Enhancement]  Color_XY and CSS-names

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [Christian-Me/node-red-contrib-ui-iro-color-picker#4]
Is it possible to support the following color modes

- Color XY        (e.g. {"x":0.1355,"y":0.0399} ) (often used bye Hue/Ikea lights)
- CSS names    ([e.g. "Red","Green","Amber"](https://www.w3schools.com/colors/colors_names.asp)) ( useful when having ALEXA/GOOGLE voice commands)

thanks a lot for considering

**Comment by Christian-Me** [comment]
Yes it can be done (like RGBW) but I don't want to overload the ui node with features not related to the original task as a color picker dashboard widget. Color converter was not the original task but as iro.js supports so many formats I made them available.
The philosophy of Node-RED is that every node should do a specific task.
The Iro color picker has already too many features.

Instead I started a new node utilizing chroma.js for a lot of color manipulation and conversion.
Give me a few days😀
I suggest to keep your flow as long as possible device independent using rgb or hsv. As soon as you send your data to a specific device convert it as needed.
Keep you updated

**Comment by Christian-Me** [comment]
Here you have it ...

https://flows.nodered.org/node/node-red-contrib-chroma

Have fun (happy for any kind of feedback)

**Comment by xX-Nexus-Xx** [comment]
Hi there,

thanks for your update.

My request was not to establish a color converter as part of your node as I already was using a node (like your chroma) for this, but to have the CSS names as list option.

This is my dashboard where I'm using your node to pick the primary color (with workaround for CSS-names)
![image](https://user-images.githubusercontent.com/2195190/126256190-f1c2324c-dfa6-46a1-9eea-08c88696252f.png)

Additionally I have RED,GREEN,BLUE button to fast select and a list-box with all the Color CSS names (in this case darkblue) .. both (button and list-box) getting converted to RGB and than feed as input to your color-picker ;)

BTW... your [node](https://flows.nodered.org/node/node-red-contrib-chroma) works great, I'm now using yours to convert "anything" into RGB .. thx a lot
