### ISSUE TITLE
output converted values

### ISSUE THREAD

**Issue by smcgann99** [Christian-Me/node-red-contrib-ui-iro-color-picker#7]
Hi,

Trying to use alexa with your node to control some led lights runing WLED firmware.

I get an input from alexa with color in hsv format which I use to update the widget color, If I click the widget the output I need is rgb.

It would be nice if the input message was converted to the type set for output. One option would be to include an object with all converted values with the new message when passed through ?

**Comment by Christian-Me** [comment]
All color conversion is happening on client side (browser). Pass through messages don't pass the client and it passes the node completely (even my own code). So the color picker is no color conversion tool. It only accept many color formats but this is based on the iro.js module (and some of my own tweaks) 

For color conversion I created a separate node ... 

https://flows.nodered.org/node/node-red-contrib-chroma

**Comment by smcgann99** [comment]
OK fair enough I have managed a work around now.
